**Mateus 1:1-17 - A Genealogia de Jesus. (Parte 4) - A libertação do medo do passado**
======================================================================================

[https://youtu.be/jIuRmE7sZOc?si=p47yet39eFs\_MoGf](https://youtu.be/jIuRmE7sZOc?si=p47yet39eFs_MoGf)

A genealogia de Jesus é apresentada no Evangelho de Mateus. A intenção do autor, segundo a minha interpretação, era **comunicar o evangelho aos judeus**. Por isso, ele escolhe incluir uma genealogia marcadamente judaica e semítica, que vai de Abraão até Jesus, passando por toda a linhagem histórica de Israel. **De Abraão a Jesus, o Cristo**, a genealogia é uma conexão profunda com a identidade do povo judeu.

Esse é um **evangelho atribuído a Mateus**. Desde os anos 1920 e 1930, muitas discussões surgiram, especialmente nos seminários americanos e reformados, sobre a autoria dos textos bíblicos. No entanto, **o importante não é tanto quem escreveu**, mas sim **se o que foi dito é fiel ao que as testemunhas oculares presenciaram**. Todos os textos antigos e recentes convergem de maneira idêntica na mensagem, o que indica uma consistência essencial.

Do ponto de vista da fé, não é essencial saber se Mateus realmente escreveu o texto. Se alguém, mesmo que não fosse Mateus, escolheu seu nome para assinar o evangelho, isso se deve ao respeito e à credibilidade que ele possuía. A tradição diz que o evangelho de Mateus foi baseado no evangelho de Marcos, **considerado o mais antigo e o mais simples de todos os evangelhos**, sem uma orientação específica para judeus ou gregos. **O Evangelho de Marcos** não possui genealogias e começa diretamente com o aparecimento de João Batista, o batismo de Jesus e sua vida adulta.

Segundo a tradição, Mateus **escreveu seu evangelho** a partir do relato de Marcos, mas com uma abordagem própria. Marcos teria baseado seu relato nas **memórias de Pedro**, o apóstolo. Pedro era um pescador simples, enquanto Mateus tinha uma formação sofisticada e era conhecido por suas habilidades com matemática e história. **Mateus era o cobrador de impostos principal na Galileia**, conhecido por Levi, e é possível que fosse descendente da tribo de Levi, a tribo dos sacerdotes de Israel.

A tribo de Levi, conforme a Lei de Moisés, vivia dos dízimos dados pelas outras tribos, pois não trabalhava em agricultura, pastoreio, carpintaria ou construção civil. Era uma **tribo dedicada ao louvor e ao culto** contínuo no templo. **Mateus, sendo levita, possuía uma conexão especial com as tradições judaicas** e um grande interesse em mostrar aos judeus como Jesus se relacionava com os profetas do Antigo Testamento.

**Por essa razão, Mateus começa seu evangelho com uma genealogia**, uma tentativa de mostrar a continuidade entre Jesus e as profecias. Ele frequentemente utiliza a expressão "para que se cumprisse as escrituras dos profetas", citando especialmente Isaías, que é a fonte mais recorrente de citações no evangelho de Mateus e em todo o Novo Testamento.

Outra característica marcante de Mateus é a **inclusão de parábolas e referências numéricas**, algo que reflete a personalidade de um cobrador de impostos, alguém que trabalhava com números e cálculos. **Mateus era um homem de números**, o que se manifesta nas parábolas que ele escolhe relatar, bem como em referências a transações financeiras, juros e investimentos. Essas características culturais e profissionais são coerentes com a personalidade do Mateus apóstolo, o que fortalece a autenticidade da narrativa.

Mateus aborda o tema financeiro com uma amplitude significativa em seu evangelho. Marcos e Lucas também falam sobre isso, mas Mateus oferece uma narrativa mais extensa e detalhada. Ele inclui, por exemplo, o **Sermão da Montanha** em sua íntegra, embora fragmentos dessa mensagem apareçam em outros contextos. A **sequência do que foi dito na Galileia** é preservada por Mateus, o que revela um espírito organizacional claro na **estrutura e arquitetura** de seu evangelho.

Para mim, é extremamente significativo que esse evangelho seja atribuído a Mateus, pois isso dialoga diretamente com a genealogia apresentada no início. Essa genealogia, como discuti nos últimos dias, não é algo que alguém poderia tomar orgulhosamente como prova de uma **herança moral ou ética impecável**. Pelo contrário, essa linhagem está longe de ser uma sequência de pessoas santas ou perfeitas. A realidade dessa genealogia é complexa e manchada, até mais do que a herança de alguns impérios antigos, onde os imperadores, mesmo que maldosos, muitas vezes tinham reinados curtos e pereciam em função de seus próprios atos.

Essa linhagem de Jesus, descrita por Mateus, tem um **significado semítico e messiânico profundo**. Ela começa com Abraão, passando pelo primeiro rei com promessas messiânicas, Davi, e chega até Jesus, o Cristo, como o cumprimento final dessas promessas. **Jesus é vinculado a Davi** no evangelho de Mateus, cumprindo as profecias que muitos esperavam. Essa conexão é notada nas expressões frequentes de pessoas clamando “**Filho de Davi, tem misericórdia de mim**” — uma frase repetida várias vezes em Mateus e Marcos, mas que quase não aparece em João e é insignificante em Lucas.

Em momentos específicos, Jesus responde de maneira provocativa às perguntas religiosas dos líderes de sua época. Em uma dessas ocasiões, ele pergunta: **"A quem se referia Davi no Salmo quando disse: ‘Disse o Senhor ao meu Senhor: assenta-te à minha direita até que eu ponha todos os teus inimigos sob os teus pés’?”**. Jesus questiona quem seria o "meu Senhor" ao qual Davi se referia, se ele próprio era o rei messiânico. **Essas provocações apontam para a compreensão de que Jesus é, de fato, o Messias prometido**, descendente de Davi e o cumprimento das profecias messiânicas.

Esses exemplos mostram como a **personalidade e a história de Mateus** estão em total harmonia com o evangelho que leva seu nome. Não tenho dúvidas de que Mateus foi o autor deste texto, pois ele narra exatamente o que se espera de alguém com sua experiência e formação. Mesmo que outra comprovação surgisse indicando uma autoria diferente, isso não mudaria a essência da narrativa. O importante é que este evangelho narra aquilo que Mateus viu, observou, anotou e redigiu, trazendo uma mensagem que tem abençoado milhões de pessoas por quase dois mil anos.

Neste estudo, muitos têm sido libertos de **medos profundos e paralisantes** ao entender o significado dessa genealogia e de como **Jesus quebra todas as maldições**. Ontem, finalizei falando sobre como o Velho Testamento trazia uma promessa de que as iniquidades dos pais seriam visitadas sobre os filhos até a terceira e quarta geração. No entanto, ao longo do próprio Velho Testamento, essa ideia foi sendo **relativizada e transformada**.

No profeta Ezequiel, vemos o clímax da mensagem que, em nome de Deus, questiona: **"Porventura, pelos pais comerem uvas verdes, embotar-se-iam os dentes dos filhos?"** E a resposta é clara: **"Não! Cada um carrega o seu próprio pecado."** Esse conceito de responsabilidade pessoal já está presente no Velho Testamento, onde encontramos alusões a essa ideia de que cada um responde por suas próprias ações. Como disse anteriormente, essa noção foi ganhando espaço e, com Jesus, atingiu uma **relativização absoluta** — uma compreensão de que não importam as linhagens, mas sim as ações de cada indivíduo.

Nos Evangelhos, a questão de “quem você é filho” praticamente inexiste; ela aparece apenas nas perguntas dos religiosos, que valorizavam tanto o **DNA e o pedigree das pessoas**. São eles que questionam: “De onde ele vem? Da Galileia? Pode vir algo bom dali?” ou “Nem sabemos de onde ele é!” A resposta de Jesus nunca é teórica ou explicativa; Ele **responde com atos de compaixão e poder**: cura enfermos, purifica leprosos, ressuscita mortos, abre os olhos aos cegos, ouvidos aos surdos, desimpede a língua dos mudos, liberta os oprimidos, e acolhe os rejeitados. **Essa é a resposta de Jesus** — Ele vive o Evangelho.

Quando João Batista, em dúvida, envia discípulos para perguntar se Jesus é aquele que deveria vir, Jesus não dá uma explicação verbal. Em vez disso, Ele **realiza uma série de curas** que cumpre as profecias de Isaías. E diz aos discípulos de João: **"Dizei-lhe o que está acontecendo."** As profecias estavam se cumprindo diante dos olhos deles: os cegos viam, os coxos andavam, e o deserto florescia. Era um sinal claro de que Jesus **encarnava as promessas dos profetas**.

Jesus continua a provocar os religiosos, perguntando: **"Ignorais os profetas e as Escrituras? Não lestes, não vistes, não aprendestes?"** Mas Sua mensagem não era um discurso teológico; era **prática existencial**. Para Jesus, o Evangelho é vida, é toque, é poder transformador que traz libertação, perdão, e redenção. **O Evangelho tem que ser assim**. Caso contrário, ele se torna apenas uma filosofia positiva ou um desafio para quem busca um estilo de vida monástico, mas deixa de ser a **boa nova** para os marginalizados, os pobres, os aflitos, e os pecadores.

Jesus deixa claro: **"Eu vim para os doentes, para os pecadores, para os que já não acreditam em si mesmos."** 

Ele veio chamá-los ao **arrependimento, à metanoia** — uma mudança radical de mente, uma nova maneira de viver. Esse é o verdadeiro Evangelho. Todo o resto — as tradições, os rituais vazios, os apelos a doações — é secundário se o Evangelho não se transformar em carne, em vida, em mudança de caráter, mente, e comportamento. **Se o Evangelho não mudar sua maneira de interpretar, julgar, e viver, então o Evangelho de Jesus ainda não chegou à sua vida**.

Hoje, vemos muitos que se denominam "evangélicos", mas onde está o **verdadeiro Evangelho** em suas vidas? Muitos carregam apenas um título, sem a qualidade da vida eterna manifestada. A maioria não passa de cristãos frequentadores de templos, mas sem o Evangelho vivo. São poucos os que realmente **vivem o Evangelho**, e esses poucos são os que sustentam a chama da fé em meio ao caos.

Mateus é um exemplo interessante desse contraste. **Ele era odiado na Galileia**, visto como um traidor, um cobrador de impostos que trabalhava para os romanos, explorando seu próprio povo. Ele não era um patriota; era considerado alguém vendido aos romanos. Pedro, Tiago, João e os demais pescadores tinham que passar pela coletoria onde Mateus estava para vender seus peixes. Mateus, ou Levi, da tribo de Levi, era visto como um aproveitador: pegava o peixe fresco e imediatamente o enviava para Jerusalém ou Cesareia Marítima, onde havia maior demanda e lucro.

Em Cesareia de Felipe, onde estavam as autoridades romanas, e em Jerusalém e Cesareia Marítima, os peixes frescos eram enviados para os ricos e os religiosos, enquanto Pedro e os demais pescadores ficavam com **peixe salgado e defumado** para comer. **Mateus estava no meio dessas transações**, o que o tornava uma figura extremamente odiada na região. Pedro, Tiago, João, André, e outros, que também foram chamados por Jesus, certamente não simpatizavam com Mateus. Havia, inclusive, uma **torcida para que Mateus não se juntasse ao grupo**.

No entanto, Mateus, embora fosse uma figura politicamente e ideologicamente oposta ao restante do grupo, foi tocado ao ver as mudanças que Jesus causava. Ele viu **pessoas duras e brutalizadas, como Pedro e Tiago, se tornarem mais humanas e sensíveis**. Esse processo de transformação nunca lhe parecera possível até ele mesmo passar por uma **convulsão interior**. Quando Jesus olhou para Mateus, viu **um coração em caos, mas com potencial de criação** e disse-lhe apenas: **"Vem e segue-me."** Mateus largou tudo — a coletoria, o dinheiro — e seguiu Jesus, sem olhar para trás. Se ele não tivesse tomado essa decisão, **não estaríamos aqui hoje falando sobre essa história**.

Mateus inicia o evangelho com uma **genealogia que representa a coerência da salvação dos pecadores**. Essa é a **genealogia da Graça de Deus**, onde encontramos desde os mais virtuosos até os mais controversos. José, o marido de Maria, é descrito como **um homem íntegro e justo**, mas a lista inclui também figuras que seriam vistas como indesejáveis. Há uma observação interessante sobre isso: **os reis mais poderosos e administradores eficientes dessa genealogia eram, muitas vezes, aqueles mais envolvidos com idolatria e práticas perversas**. Enquanto os reis piedosos se dedicavam ao templo e aos mandamentos, os mais corruptos se voltavam para exércitos, fortalezas e guerras.

Para mim, Mateus é o verdadeiro autor desse texto, e sua **vida é totalmente coerente com a genealogia que apresenta**. Ele se identifica com essa linhagem ao dizer: **"Essa é a minha genealogia também"**. Ele se vê representado pelos ancestrais da tribo de Levi, como Arão, o mesmo que fez o bezerro de ouro. E, mesmo com toda essa bagagem, **Jesus olhou para ele, o chamou e o desejou**. Hoje, Mateus carrega o testemunho de alguém que foi transformado, que viu, tocou e viveu a mensagem de Jesus.

Se um homem como Mateus pôde se transformar e ser acolhido, quem não pode? 

**Quem tem um problema político ou ideológico tão grande que o impeça de se converter?** Mateus é o exemplo de que **não importa de onde você venha, há um caminho e uma vereda para você**. Ele é quem mais enfatiza que **a porta e o caminho são estreitos**. Ele entende o poder que o dinheiro e o apego material podem ter sobre o coração humano. Por isso, Mateus nos ensina que, se recebemos algo, é para que possamos **servir e dar em amor**. Ele repete essa mensagem, sabendo que as **capacitações de Deus são para servir, amar e beneficiar aos outros**.

Mateus, beneficiário extraordinário da Graça, mais que muitos outros apóstolos, entende a profundidade do chamado. Ele vem daquela **região da Galileia, onde tudo é sombrio e desolador**, um lugar distante da luz. E mesmo assim, ele encontrou a **luz de Jesus**, que não apenas iluminou seu caminho, mas o transformou em um mensageiro do Evangelho, uma testemunha viva de que, onde quer que o sol nasça, a graça de Deus pode florescer.

Na Galileia, o sol nasce depois e se põe antes devido às montanhas que a cercam. Em algumas épocas do ano, ao descer da Alta Galileia em direção a Tiberíades, por volta das quatro horas da tarde, o sol já está se pondo, deixando a região sob uma sombra projetada. **A Galileia é um lugar de sombra, uma região sombria**. Para exemplificar, é como Balneário Camboriú, no Brasil, onde, devido aos arranha-céus de até 150 andares, a praia entra na sombra cedo, às três horas da tarde. Assim é a Galileia, um lugar onde a luz do sol demora a brilhar.

Trazer Pedro para o Evangelho já era algo natural, pois ele era um dos “pobretões” da região, alguém politicamente aflito, revoltado, e fazia parte do público alvo de Jesus. **Mateus, no entanto, era diferente**: ele era rico, explorador, antinacionalista, sem vínculo com seu povo, apenas com o lucro. Era um dos menos prováveis de serem chamados, o que certamente causou ciúmes e desconforto entre os outros apóstolos, que agora precisavam **aprender a aceitar Mateus, ouvi-lo, ser irmãos dele**. Imaginem a conturbação entre aqueles apóstolos pobres ao ver **o grande explorador da Galileia sendo chamado por Jesus**.

Mateus, por outro lado, é notável por sua discrição entre os apóstolos. 

Em seu evangelho, ele se refere a si mesmo de forma distante, sem destacar seu papel. 

Ele relata seu chamado como algo simples: **“Passando, chamou Levi, que estava na coletoria, e ele largando tudo, seguiu.”** Diferente de João, que se refere a si como “o discípulo a quem Jesus amava,” ou Marcos, que insere uma nota pessoal no episódio do jovem nu que corre, Mateus nunca fala de si com destaque. Lucas, que faz questão de se identificar e de descrever o processo de pesquisa acurada que realizou, é explícito quanto a sua autoria e seu método.

Mateus, no entanto, **fala da genealogia de Jesus** — uma linha repleta de pessoas que não eram moralmente exemplares, mas que foram alcançadas pela graça. **“Onde abundou o pecado, superabundou a graça,”** e esta genealogia é uma lista de pessoas marcadas pelo pecado, como Manassés, mas que ainda assim compõem a linhagem de Jesus. **Mateus era o mais malvisto dos apóstolos**, mais até que Simão, o zelote. Simão era um extremista, mas ele lutava por uma sociedade justa e via a resistência aos romanos como um dever sagrado. Quando ele encontrou o Evangelho, entendeu que a verdadeira revolução é feita pelo **Espírito de Cristo, e que as armas da nossa milícia não são carnais**, mas espirituais, para derrubar fortalezas e anular sofismas.

Mateus, contudo, se aproxima discretamente, reconhecendo sua própria condição. Ele não se enaltece; ao contrário, sabe que, **pela graça, também encontrou um lugar**. Ele simboliza aqueles que, apesar de sua condição, foram **chamados para andar com Jesus**. Hoje, ao estudar essa genealogia, aprendemos lições profundas sobre a graça: a genealogia não oferece nada além de **graça, graça, graça** — favor imerecido.

Para finalizar, destaco três lições essenciais que essa genealogia nos ensina, lições que desejo que você guarde no coração. **Independentemente de onde você esteja, de onde tenha vindo ou da sua situação atual**, essa mensagem é para você.

Deus acolhe pessoas de todos os tipos, com histórias e origens diversas, da mesma forma que Ele acolheu **Pedro e Mateus**, e até os **irmãos zelotes de esquerda revolucionária**. No círculo dos discípulos, havia desde figuras impulsivas, como João e Tiago, os Boanerges, até as mais serenas e discretas, como André e Filipe. **Há um lugar para todos** nessa genealogia de Jesus, e também para cada um de nós. Isso significa que há um espaço para mim e para você, não importa quem somos.

**A primeira lição** que essa genealogia me ensina é simples: 

**"Não sei por que fui chamado, mas sei que ouvi a Sua voz."** 

Você pode repetir isso em voz alta, onde quer que esteja, talvez até balbuciando: **"Não sei por que fui chamado, mas sei que ouvi a Sua voz."** Assim como Mateus, que ouviu o chamado de Jesus para segui-lo, você pode dizer: **"Eu ouvi a Sua voz e segui."**

**A segunda lição** é reconhecer que muitos outros poderiam estar em nosso lugar, mas estranhamente, hoje eu estou onde estou. Não porque eu merecia, mas porque a graça me chamou e encontrei meu lugar. Repita comigo: 

**"Muitos outros poderiam estar em meu lugar, mas hoje eu estou no lugar que é meu por causa da Graça."** 

Foi essa mesma graça que chamou Mateus, alguém improvável, e o incluiu na linhagem que escreveu o evangelho. Essa mesma graça me colocou aqui, mesmo que muitos melhores pudessem ocupar esse lugar.

Eu, Caio Fábio, reconheço que **minha vida inteira foi um presente da Graça**. Meu pai, mesmo sendo agnóstico, dedicou minha vida a Deus quando eu nasci, no hospital, em Manaus. Sem saber se Deus existia, ele disse: **"Se há Deus, eu ofereço esse filho para que ele seja alguém cheio da palavra da vida de Deus."** E hoje sei que o lugar que ocupo é, de fato, meu, concedido pela Graça.

Por isso, não tenho ciúmes ou inveja de ninguém. Não quero ser como ninguém, não preciso imitar ou repetir ninguém. O máximo que posso fazer é me ajoelhar com a Bíblia aberta, **tentando ver o mundo através do olhar de Jesus**. Esse olhar, moldado pelo Evangelho, me ajuda a enxergar todas as coisas — ciência, filosofia, teologia — sob a luz do que Jesus ensinou, apenas pela Graça e misericórdia, sem mérito algum meu.

Deus me manteve vivo, mesmo nas inúmeras vezes que poderia ter partido. Desde pequeno, escapei da morte várias vezes. Quando eu era bebê, adoeci gravemente e sobrevivi. Aos seis anos, caí de um barco no Rio Negro, enredado nas cordas, lutando para subir enquanto via apenas a sombra do barco na água escura. Quando já pensava que não sairia, uma corda pesada caiu na água, e eu me agarrei a ela e fui puxado para cima. A respiração que dei foi **salvação pura**.

Assim, a Graça me sustentou, me preservou e continua a me guiar.

Desde criança, eu vivia no limite: brincava com carros passando, desviava, escapava por pouco. Amigos meus não tiveram a mesma sorte — alguns morreram, outros foram atropelados. Eu era o mais ousado, o que desviava sempre a última hora, e ouvi muitas vezes que um dia morreria. Na adolescência, vieram as experiências intensas e perigosas: **drogas, overdoses, brigas, ameaças** — inclusive no ministério. Nunca recuei. Estive em lugares desde **palácios presidenciais até favelas, presídios, e entre os rejeitados da sociedade**. Meu caminho sempre foi marcado por extremos, enfrentando perigos de todos os tipos, e posso dizer com segurança que **nunca dei a mínima para os riscos**.

Hoje, sei que **outros poderiam estar no meu lugar**, mas Deus me colocou exatamente onde estou. **Não tenho respostas para as perguntas do diabo**; eu apenas sigo com a missão que me foi dada: **pregar o Evangelho da Graça de Deus**. Quem tiver ouvidos para ouvir, que ouça. **Essa graça transforma e liberta**, e quem a entende não faz mais perguntas tolas, pois **tudo é graça, tudo é renovação**. Quando Cristo nasce em nossa história, nossa história passada morre, e a **Graça reina**.

Minha história é **cheia de graça, cheia de vida e cura**. Já vi muitos serem libertos, demônios expulsos, mentes atormentadas serem pacificadas, reconciliações e aproximações acontecerem. Deus me deu essa história, e **ela marcou e continuará marcando gerações**, pois é uma obra do Espírito de Deus, não do homem. Louvado seja o nome de Jesus! Eu sei que outros poderiam estar aqui, mas **Deus me colocou neste lugar, e é o meu lugar**.

**A terceira lição** que desejo compartilhar é: 

**“Eu não gosto de tudo que sou, mas sei que Deus me ama apesar de mim.”** 

Estou em um processo, em transformação, como Paulo disse: esquecendo-me do que ficou para trás, prossigo para o alvo. Até Paulo tropeçou, tanto antes quanto depois de conhecer Jesus. Ele era um homem colérico, impulsivo, assim como Pedro, e eu me identifico com ele. Sempre fui aquele que **arrombava portas e derrubava muralhas**, às vezes me precipitando.

Paulo também se precipitou, como no caso da discussão com Barnabé por causa de João Marcos, um desentendimento que levou à separação dos dois. Ou quando ele falou com dureza sobre entregar alguém a Satanás para destruição da carne — algo que Jesus jamais faria. **Jesus sempre agiu com misericórdia**, como no caso de Pedro, quando disse: **“Simão, Simão, Satanás pediu para peneirar você, mas eu roguei por ti.”** Aprendo com Jesus, não com Paulo, e é por isso que **nunca entregarei ninguém a Satanás**.

Paulo, mais tarde, reconheceu suas precipitações. Em 2 Coríntios, ele pede perdão pelas palavras duras, por talvez ter ferido aqueles que poderiam se arrepender. Ele aprendeu e admitiu seu erro. Que possamos aprender com isso: seguir com graça, evitando julgamentos precipitados, e lembrando sempre do olhar misericordioso de Jesus.

Em suas cartas, Paulo às vezes se exaltava, perdendo a paciência. Ele chegou a pedir licença para ser “insensato”, reconhecendo que, ao falar de si mesmo, poderia parecer insensato. Paulo sabia que havia **sacrificado mais pelo Evangelho do que qualquer outro**, mas também reconhecia que essa insistência em falar de seus feitos talvez fosse mais apropriada para um texto escrito por Lucas, alguém que relataria suas tragédias e vitórias pela fé. Mesmo assim, ele falava. **Paulo era humano**, e como todos nós, às vezes se arrependia das palavras impulsivas e voltava atrás, como no caso de sua reconciliação com Barnabé e João Marcos.

Ele era uma figura tão à frente de sua época que, mesmo hoje, muitos ainda tentam acompanhá-lo. **Paulo compreendia e transmitia a liberdade em Cristo**: em Cristo, não há diferença entre homem e mulher, livre e escravo, judeu e grego. Ele reconhecia que algumas de suas orientações eram circunstanciais, baseadas na cultura de sua época, e o Evangelho de Jesus sempre vai além dessas limitações culturais. **Jesus é nossa chave de interpretação**, e quando entendemos isso, nenhuma nova ideia justa da sociedade nos surpreende, pois Jesus já havia proposto algo maior e mais profundo.

Paulo também não gostava de tudo o que era e incentivava a desenvolver a salvação, pois ele sabia que **estamos todos em um processo de crescimento**. Somos seres inacabados, e assim como Paulo, cada um de nós está em uma jornada de transformação. Somos chamados a crescer em direção à “Nova Jerusalém”, uma **cidade aberta e eterna** em Cristo, onde não há teto ou limitação, apenas o crescimento e desenvolvimento na luz de Deus.

Eu estou em paz com o fato de que não sou perfeito. **Estou coberto pela graça de Cristo**, e isso me permite tratar de mim mesmo sem culpa ou neurose. Todos os dias, olho para dentro e vejo que ainda há trabalho a ser feito. Há **sentimentos a serem revistos, escolhas a serem refeitas, e emoções a serem tratadas**. Esse processo de crescimento acontece em silêncio, na comunhão entre mim e o Espírito Santo, pois eu sei que **Deus me ama apesar de mim**.

Esse amor divino me transforma, fazendo com que, quanto mais humano eu me torno em Cristo, **mais divino também me torno**. Como Pedro diz, somos chamados a não alimentar os **“vãos comportamentos que herdamos de nossos pais”**. Não estou aqui para glorificar uma herança cultural ou uma genealogia imperfeita; sou um filho de Deus em Cristo Jesus. Quanto mais me pareço com Jesus, mais rejeito os padrões vazios e maldições culturais.

Pedro nos lembra que essa **“semente divina” cresce em nós**. Paulo também fala dessa transformação em Cristo, e João nos diz que, quando o virmos, seremos como Ele. Esse é o propósito da nossa existência: **esquecer o que ficou para trás e prosseguir para o alvo**, para o prêmio da vocação em Cristo Jesus.

Que o Espírito Santo permita que essa mensagem alcance corações abertos, **trazendo paz, fundamentação e transformação**. Que sejamos fortalecidos no Espírito para viver uma vida mais próxima do chamado de Cristo Jesus. **Que todos que têm ouvidos, ouçam**.

Em nome de Jesus, amém.
